### PR TITLE
Applying code version from ESOUI (minus minor formatting)

### PR DESCRIPTION
**Pull request by MysteryDragon**
First of all, I must introduce the reasons why I'm proposing PR **here**.
I searched for RaidNotifier repository, and this particular fork of kyoma's repository seems most relevant 'cause:
- it heads from ESOUIMods company (which might be related to esoui.com, but I found no any particular information about that)
- it contains most updated version of the addon

Now, for the part about **why** I do propose this changings at all.
If you'll download RaidNotifier from esoui.com, and check file differences (by _diff_ command or somehow else), you'll find out that _actual_ code and _nominal_ code (here) are not exactly equal.
It may be fine for now, but if this repository meant to be some kind of representation of addon code, it might be crucial to keep exactly _identical_ copy of code. The reason is if some person will start to change the code and will relate on repository's code as right state of addon, eventually he may touch that part of addon which is different.
So when addon will be updated it will receive not only _intended_ changes, but also _unintended_ changes which are present for now.
(In worst case if such update would be made as plain direct file copying we may end with inconsistent state at all.)

So I propose most reasonable solution IMO: I applied actual version of addon (minus some space-formatting issues to keep diff cleaner here), and propose to merge it into your repository.
You can easily check that now there are no any significant differences between addon code and this code, using _diff_ command or some other instruments.

Another option in my opinion is to apply your version of addon to esoui.com, but it's more risky since current esoui.com version is tested by many players, and I assume that this repository's version is not so well tested. So it's not really good to make unknown changes without ability to fix issues fast (which cannot be provided by addon maintainers).

Thanks for attention.

### CODE REVIEW

**Comment by Sharlikran** [comment]
@MysteryDragon So all of the addons I host are for my own personal use. I have permission to have them publicly visible either because the author gave permission or there is a license.

What I do with them usually is that I have removed embedded libraries or libstub, usually.

Kyoma had made some changes to LibGroupSocket and I didn't like them. So I made my own version of it so it didn't conflict with Sirinsidiator's version.

However, all that has been changed now. I have not used or tested Kyoma's version in a while because I typically don't do trials. I am not the mad crazy DPS machine most people want.

I will try to test Kyoma's official version sometime in the future and I will see how well it works and what kinds of conflicts there are. If for some reason I find that his version works fine and I don't really need to change the official ESOUI code then I will decide at that time what to do with it.

> I applied actual version of addon (minus some space-formatting issues to keep diff cleaner here), and propose to merge it into your repository.

I am going to close this for now because it looks like your version is just the ESOUI version with the formatting as you mentioned.

Everything I host I have permission to do so for archive reasons, but unless it is something I am actively updating it just sits here and collects dust. None of the authors come to me and collaborate with me or anything and I don't upload these version to ESOUI.

Again, nothing against your idea but as is sometimes said, "These are not the droids you are looking for"

**Comment by MysteryDragon** [comment]
@Sharlikran yeah, sure, I just misunderstood the purpose of your repository at the first place.
Thanks for clarification!

**Comment by Sharlikran** [comment]
@MysteryDragon After looking at things I see that I already have the changes I wanted for them.

branch dev-shar : [ESO-RaidNotifier](https://github.com/ESOUIMods/ESO-RaidNotifier/archive/dev-shar.zip)
branch master: [LibGroupSocket](https://github.com/ESOUIMods/LibGroupSocket/archive/master.zip)

You need those exact versions to test with. I don't know if they work but they should.

As far as changing spaces and such, that just makes a lot of commit noise. It's best to not do that. Just leave it. Don't format the code to make it look prettier it works fine how it is.

**Comment by Sharlikran** [comment]
@MysteryDragon I just went through the current version. If you still play and you still do non vet trials or whatever, I would be curious if this version works properly.

**Comment by MysteryDragon** [comment]
@Sharlikran sorry, just to clarify: do you want to ask me to check if your version of RaidNotifier works properly?
Yeah, I do non-vet trials once per week usually, so as vet trials. So I can check your version if you meant that and I didn't mixed smth up :D
(I analyzed diff between your version and "master"-version of base repository, and according to that your version should work fine; but won't hurt to check :D)

**Comment by Sharlikran** [comment]
> Yeah, I do non-vet trials once per week usually, so as vet trials. So I can check your version if you meant

Yes that is what I meant

**Comment by MysteryDragon** [comment]
> Yes that is what I meant, when you do your non vet trials. Because it probably doesn't matter whether or not it is a vet trial. Coordinate that with others that use the Ultimate sharing though please.
> 
> I'm trying to see if this can become an official LibStub free version.

@Sharlikran sorry for late respond, didn't done much trials lately. But today I checked it, looks like it works fine.
Unfortunately I don't know anyone who's using Ultimate sharing or who's willing to use it instead of Hodor (and Hodor blocks RaidNotifier's Ultimate sharing afaik). So I can't say anything about it.

**Pull request closed without merging**
